language: generic 
sudo: required
services:
 - docker

before_install:
  - docker build -t bassouline/docker-react -f dockerfile.dev .

script:
  - docker run -e CI=true bassouline/docker-react npm run test